config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  resources :movements
  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/movement.rb
class Movement < ApplicationRecord
  belongs_to :user
  enum movement_type: { entrance: 1, exit: 2 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :users
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/movements_controller.rb
class MovementsController < ApplicationController
    def index
        @movements = Movement.all.limit(50)
    end

    def new
        @movement = Movement.new
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/movements_helper.rb
module MovementsHelper
end

app/views/layouts/_dashboard.html.haml
%body
  %header#header.header.fixed-top.d-flex.align-items-center
    .d-flex.align-items-center.justify-content-between
      %a.logo.d-flex.align-items-center{href: "index.html"}
        %img{alt: "", src: "assets_files/img/logo.png"}/
        %span.d-none.d-lg-block NiceAdmin
      %i.bi.bi-list.toggle-sidebar-btn
    / End Logo
    .search-bar
      %form.search-form.d-flex.align-items-center{action: "#", method: "POST"}
        %input{name: "query", placeholder: "Search", title: "Enter search keyword", type: "text"}/
        %button{title: "Search", type: "submit"}
          %i.bi.bi-search
    / End Search Bar
    %nav.header-nav.ms-auto
      %ul.d-flex.align-items-center
        %li.nav-item.d-block.d-lg-none
          %a.nav-link.nav-icon.search-bar-toggle{href: "#"}
            %i.bi.bi-search
        / End Search Icon
        %li.nav-item.dropdown
          %a.nav-link.nav-icon{"data-bs-toggle" => "dropdown", href: "#"}
            %i.bi.bi-bell
            %span.badge.bg-primary.badge-number 4
          / End Notification Icon
          %ul.dropdown-menu.dropdown-menu-end.dropdown-menu-arrow.notifications
            %li.dropdown-header
              You have 4 new notifications
              %a{href: "#"}
                %span.badge.rounded-pill.bg-primary.p-2.ms-2 View all
            %li
              %hr.dropdown-divider/
            %li.notification-item
              %i.bi.bi-exclamation-circle.text-warning
              %div
                %h4 Lorem Ipsum
                %p Quae dolorem earum veritatis oditseno
                %p 30 min. ago
            %li
              %hr.dropdown-divider/
            %li.notification-item
              %i.bi.bi-x-circle.text-danger
              %div
                %h4 Atque rerum nesciunt
                %p Quae dolorem earum veritatis oditseno
                %p 1 hr. ago
            %li
              %hr.dropdown-divider/
            %li.notification-item
              %i.bi.bi-check-circle.text-success
              %div
                %h4 Sit rerum fuga
                %p Quae dolorem earum veritatis oditseno
                %p 2 hrs. ago
            %li
              %hr.dropdown-divider/
            %li.notification-item
              %i.bi.bi-info-circle.text-primary
              %div
                %h4 Dicta reprehenderit
                %p Quae dolorem earum veritatis oditseno
                %p 4 hrs. ago
            %li
              %hr.dropdown-divider/
            %li.dropdown-footer
              %a{href: "#"} Show all notifications
          / End Notification Dropdown Items
        / End Notification Nav
        %li.nav-item.dropdown
          %a.nav-link.nav-icon{"data-bs-toggle" => "dropdown", href: "#"}
            %i.bi.bi-chat-left-text
            %span.badge.bg-success.badge-number 3
          / End Messages Icon
          %ul.dropdown-menu.dropdown-menu-end.dropdown-menu-arrow.messages
            %li.dropdown-header
              You have 3 new messages
              %a{href: "#"}
                %span.badge.rounded-pill.bg-primary.p-2.ms-2 View all
            %li
              %hr.dropdown-divider/
            %li.message-item
              %a{href: "#"}
                %img.rounded-circle{alt: "", src: "assets_files/img/messages-1.jpg"}/
                %div
                  %h4 Maria Hudson
                  %p Velit asperiores et ducimus soluta repudiandae labore officia est ut...
                  %p 4 hrs. ago
            %li
              %hr.dropdown-divider/
            %li.message-item
              %a{href: "#"}
                %img.rounded-circle{alt: "", src: "assets_files/img/messages-2.jpg"}/
                %div
                  %h4 Anna Nelson
                  %p Velit asperiores et ducimus soluta repudiandae labore officia est ut...
                  %p 6 hrs. ago
            %li
              %hr.dropdown-divider/
            %li.message-item
              %a{href: "#"}
                %img.rounded-circle{alt: "", src: "assets_files/img/messages-3.jpg"}/
                %div
                  %h4 David Muldon
                  %p Velit asperiores et ducimus soluta repudiandae labore officia est ut...
                  %p 8 hrs. ago
            %li
              %hr.dropdown-divider/
            %li.dropdown-footer
              %a{href: "#"} Show all messages
          / End Messages Dropdown Items
        / End Messages Nav
        %li.nav-item.dropdown.pe-3
          %a.nav-link.nav-profile.d-flex.align-items-center.pe-0{"data-bs-toggle" => "dropdown", href: "#"}
            %img.rounded-circle{alt: "Profile", src: "assets_files/img/profile-img.jpg"}/
            %span.d-none.d-md-block.dropdown-toggle.ps-2 K. Anderson
          / End Profile Iamge Icon
          %ul.dropdown-menu.dropdown-menu-end.dropdown-menu-arrow.profile
            %li.dropdown-header
              %h6 Kevin Anderson
              %span Web Designer
            %li
              %hr.dropdown-divider/
            %li
              %a.dropdown-item.d-flex.align-items-center{href: "users-profile.html"}
                %i.bi.bi-person
                %span My Profile
            %li
              %hr.dropdown-divider/
            %li
              %a.dropdown-item.d-flex.align-items-center{href: "users-profile.html"}
                %i.bi.bi-gear
                %span Account Settings
            %li
              %hr.dropdown-divider/
            %li
              %a.dropdown-item.d-flex.align-items-center{href: "pages-faq.html"}
                %i.bi.bi-question-circle
                %span Need Help?
            %li
              %hr.dropdown-divider/
            %li
              %a.dropdown-item.d-flex.align-items-center{href: "#"}
                %i.bi.bi-box-arrow-right
                %span Sign Out
          / End Profile Dropdown Items
        / End Profile Nav
    / End Icons Navigation
  / End Header
  / ======= Sidebar =======
  %aside#sidebar.sidebar
    %ul#sidebar-nav.sidebar-nav
      %li.nav-item
        %a.nav-link.collapsed{href: "movements"}
          %i.bi.bi-grid
          %span Dashboard
  / End Sidebar
  %main#main.main
    = yield
  / End #main
  / ======= Footer =======
  %footer#footer.footer
    .copyright
      © Copyright
      = succeed "." do
        %strong
          %span NiceAdmin
    .credits
      / All the links in the footer should remain intact.
      / You can delete the links only if you purchased the pro version.
      / Licensing information: https://bootstrapmade.com/license/
      / Purchase the pro version with working PHP/AJAX contact form: https://bootstrapmade.com/nice-admin-bootstrap-admin-html-template/
      Designed by
      %a{href: "https://bootstrapmade.com/"} BootstrapMade
  / End Footer
  %a.back-to-top.d-flex.align-items-center.justify-content-center{href: "#"}
    %i.bi.bi-arrow-up-short

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{content: "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title FinanceRails
    %meta{content: "width=device-width,initial-scale=1", name: "viewport"}/
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag "application"
    = javascript_importmap_tags
    %link{href: "assets_files/img/favicon.png", rel: "icon"}/
    %link{href: "assets_files/img/apple-touch-icon.png", rel: "apple-touch-icon"}/
    / Google Fonts
    %link{href: "https://fonts.gstatic.com", rel: "preconnect"}/
    %link{href: "https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Nunito:300,300i,400,400i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i", rel: "stylesheet"}/
    / Vendor CSS Files
    %link{href: "assets_files/vendor/bootstrap/css/bootstrap.min.css", rel: "stylesheet"}/
    %link{href: "assets_files/vendor/bootstrap-icons/bootstrap-icons.css", rel: "stylesheet"}/
    %link{href: "assets_files/vendor/boxicons/css/boxicons.min.css", rel: "stylesheet"}/
    %link{href: "assets_files/vendor/quill/quill.snow.css", rel: "stylesheet"}/
    %link{href: "assets_files/vendor/quill/quill.bubble.css", rel: "stylesheet"}/
    %link{href: "assets_files/vendor/remixicon/remixicon.css", rel: "stylesheet"}/
    %link{href: "assets_files/vendor/simple-datatables/style.css", rel: "stylesheet"}/
    / Template Main CSS File
    %link{href: "assets_files/css/style.css", rel: "stylesheet"}/
  %body
    %p.notice= notice
    %p.alert= alert
    = render 'layouts/dashboard'
    %script{src: "assets_files/vendor/apexcharts/apexcharts.min.js"}
    %script{src: "assets_files/vendor/bootstrap/js/bootstrap.bundle.min.js"}
    %script{src: "assets_files/vendor/chart.js/chart.umd.js"}
    %script{src: "assets_files/vendor/echarts/echarts.min.js"}
    %script{src: "assets_files/vendor/quill/quill.js"}
    %script{src: "assets_files/vendor/simple-datatables/simple-datatables.js"}
    %script{src: "assets_files/vendor/tinymce/tinymce.min.js"}
    %script{src: "assets_files/vendor/php-email-form/validate.js"}
    / Template Main JS File
    %script{src: "assets_files/js/main.js"}

app/views/movements/_form.html.haml
= form_with model: movement do |f|
  - if movement.errors.any?
    %div{style: "color: red"}
      %h2
      = pluralize(product.errors.count, "error")
      prohibited this product from being saved:
      %ul
      - movement.errors.each do |error|
        %li= error.full_message
      .mb-3
      = f.label :description, class: "form-label", for: "description"
      = t.text_field :description, class: "form-control"
      .mb-3
      = f.label :description, class: "form-label", for: "Movement type"
      = f.select :movement_type, [["Selecione..", ""], ["Entrada", 1], ["Saída", 2]], { include_blank: false }, class: "form-control"
      .mb-3.col-md-2
      = f.label :value, class: "form-label"
      = f.text_field :value, id: "currency", class: "form-control", placeholder: "0.00"
      .mb-3.d-flex.justify-content-end
    = f.submit value: "Salvar", class: "btn btn-primary"

app/views/movements/index.html.haml
%section.section
  .row
    .col-lg-12
      .card
        .card-body
          %h5.card-title Movements
          / Table with stripped rows
          .table-responsive
            %table.table.datatable
              %thead
                %tr
                  %th Id
                  %th Descrição.
                  %th Valor
                  %th Data de Criação
              %tbody
                - @movements.each do |movement|
                  %tr
                    %td= movement.id
                    %td= movement.description
                    %td= movement.value
                    %td= movement.created_at
            / End Table with stripped rows
          .d-flex.justify-content-end
            =link_to new_movement_path, class: "btn btn-sm btn-primary" do
              Adicionar

app/views/movements/new.html.haml
%section.section
  .row
    .col-12
      .card
        .card-body
          %h5.card-title Cadastrar Movimentação
          = render "form", movement: @movement